### ISSUE TITLE
README.md not Useful

### ISSUE THREAD

**Issue by ghost** [QuickToBeSlow/Bonk_Remake#4]
Hello there,
recently i tried to learn about neural networks and found this project. unfortunately the README.md is not really detailed how to use this and i can't really figure out how it works. it would be desirable if this would be updated.

thanks in advance your Droppsi

**Comment by QuickToBeSlow** [comment]
I can make things more clear in the README, sure. Also, for learning more about neural networks I would advise looking at other sources such as The Coding Train's series on Neural evolution: https://www.youtube.com/watch?v=c6y21FkaUqw
He's very instructive and all around a great guy to learn from if you haven't seen his content.

Let me know if you have any other questions, but be aware I'm busy with college right now so I can't guarantee I'll get back to you right away.
